### ISSUE TITLE
xls / csv export options

### ISSUE THREAD

**Issue by andylolz** [mysociety/yournextmp-popit#176] opened 2015-02-01 19:39 UTC
Do these export options already exist? I’ve noticed people on twitter looking for spreadsheets of candidate data, and I wonder whether this is the format they’re expecting it in. Perhaps we should offer this as an export option.

**Comment by symroe** [comment] 2015-02-01 22:23
Duplicate of #96, and PR here: #177

**Comment by symroe** [comment] 2015-02-01 22:24
But you're absolutely right, this is a high priority and I've been sitting on the code for some time now :/

**Closed by symroe** 2015-02-01 22:23 UTC

**Comment by andylolz** [comment] 2015-02-02 08:20
Ah! Apologies – I searched issues for “xls” and some other terms, but managed to miss these.

I should really sort out [datapipes](http://datapipes.okfnlabs.org/) so it’s able to do this transformation for you on the fly – then you could URL shorten that as a massively hacky solution!
