### ISSUE TITLE
Why is candidate gender given such prominence on their profile?

### ISSUE THREAD

**Issue by equivalentideas** [mysociety/yournextmp-popit#142] opened 2015-01-15 00:38 UTC
Interested in the chosen order of the data on the candidate profile page (for example https://yournextmp.com/person/885/anne-begg).

**Comment by mhl** [comment] 2015-01-16 14:56
There isn't any particular reason for that: when I added the gender field, the existing fields were (and still are) roughly in order of the complexity of their underlying data storage, so I put it in with the fields that are similarly simple in their Popolo data model representation, like name and email address.

I'm quite happy to reorder these if people think that it appears to put undue prominence on gender? (I'd like to still include that data somewhere, since it's useful for measuring one aspect of diversity.)

**Comment by equivalentideas** [comment] 2015-01-19 22:29
Hi @mhl thanks for that. Maybe a better order would be by what is easiest to find out, to encourage citizens to dive in and get some quick wins. Gender may be one of the easiest here. I was just interested in the thinking behind this choice.

**Comment by andylolz** [comment] 2015-02-17 10:39
I think #159 addressed this – gender bumped way down the list.

In reference to @equivalentideas’s last point: The information is not ordered by ease of discovery now, but I think it probably is in order of usefulness. At this stage (now that we have a lot of data in there) that’s probably preferable.

**Comment by mhl** [comment] 2015-02-17 10:49
@andylolz Yeah, I'm happy that the issue is addressed now, so I'll close this

**Closed by mhl** 2015-02-17 10:49 UTC

**Comment by equivalentideas** [comment] 2015-02-17 20:21
Thanks @andylolz and @mhl , the new profile page layout is very clear, great job.
